ML-01 related changes
EglitisMaikls/Magebit_learning pull request #1
Opened 2023-10-07 17:50 UTC by EglitisMaikls

Magento widget and PLP template

2023-10-09 07:59 UTC, ronaldsrmagebit requested changes

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +<?php
Not 100% sure if the copyright block was mentioned in the ML01 learning, but that is missing.
```
/**
 * @copyright Copyright (c) 2023 Magebit (https://magebit.com/)
 * @author    <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
```

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +class PageList extends Template implements BlockInterface
Class docblock isn't necessary.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +    protected $_template = "page-list.phtml";
Missing class property docblock.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +        Template\Context $context,
You can just import `use Magento\Framework\View\Element\Template\Context;` and in the constructor you can just use `Context $context`

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +    public function __construct(
Missing method docblock.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +    public function getDisplayMode()
You can provide the method return type.
```php
public function getDisplayMode(): int
{
    return (int) $this->getData('display_mode');
}
```

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +    public function getSelectedPageIds()
You can provide the method return type.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +    public function getCmsPageById($pageId)
You can provide the method return type.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +    public function getCmsPages()
You can provide the method return type.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +    protected $pageRepository;
Missing method type property.

`protected PageRepositoryInterface $pageRepository;`

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +        PageRepositoryInterface $pageRepository,
Since this is run on PHP 8.1 (or 8.2) you can do property promotion.
Ref: https://stitcher.io/blog/constructor-promotion-in-php-8 and https://stitcher.io/blog/php-81-readonly-properties

Example case:
```php
public function __construct(
    private readonly PageRepositoryInterface $pageRepository
}
```
Which means you don't need to declare `protected $pageRepository;` and don't need to initialize ` $this->pageRepository = $pageRepository;`

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/etc/module.xml
> +<?xml version="1.0"?>
Missing copyright docblock.
```
<!--
/**
 * @copyright Copyright (c) 2023 Magebit (https://magebit.com/)
 * @author    <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
 -->
```

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/etc/widget.xml
> +<!--
Missing copyright docblock

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/registration.php
> +
Missing copyright docblock. As well missing declare(strict_types=1);

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +
Since PHP 7, you can declare that PHP doesn't do specific things and force it to be more strict
```php
declare(strict_types=1);
```
This is always declared before the namespace.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/view/frontend/templates/page-list.phtml
> +/**
Missing copyright docblock.

 Additionally missing the escaper. In theory, when ever you echo output, you should always run it via escaper.

As well you can declare docblock for it so PHPStorm provides available methods, the same goes for the block class.
```php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magebit\PageListWidget\Block\Widget\PageList $block */
```

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/view/frontend/templates/page-list.phtml
> +    <?php if ($block->getDisplayMode() == 1): ?>
You should always do strict compare instead of loose compare.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/view/frontend/templates/page-list.phtml
> +                <a href="<?php echo $block->getUrl('cms/page/view', ['page_id' => $page->getId()]); ?>">
No need for `<?php echo`, you can use the shorthand echo `<?=` as seen on the line 8. As well missing escaper.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/view/frontend/templates/page-list.phtml
> +                    <?php echo $page->getTitle(); ?>
The same as above

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/view/frontend/templates/page-list.phtml
> +                    <a href="<?php echo $block->getUrl('cms/page/view', ['page_id' => $page->getId()]); ?>">
The same as above

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/view/frontend/templates/page-list.phtml
> +                        <?php echo $page->getTitle(); ?>
The same as above

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/list/items.phtml
> +/**
You can replace the original Magento copyright block with the one that was mentioned earlier.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/list/items.phtml
> +
These new lines can be removed. Also, to me, it seems that the line indentions are incorrect.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/list/items.phtml
> +/**
As well, you can add a PHP comment in the exact place, where changes were made, as this is mostly a copy-paste from the Magento template file.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +/**
You can replace the original Magento copyright block with the one that was mentioned earlier.
As well, you can add a PHP comment in the exact place, where changes were made, as this is mostly a copy-paste from the Magento template file.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/attributes.phtml
> +/**
Missing copyright block.
Missing the escaper class.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/attributes.phtml
> +$_product = $block->getProduct();
`$_` shouldn't be used as that is really old Magento 1 convention for "declaring" private properties. You can just do `$product`.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/attributes.phtml
> +$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
The same as above.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/attributes.phtml
> +<?php if ($_additional = $block->getAdditionalData()) :?>
The same as above.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/attributes.phtml
> +        <?php endif; endforeach; ?>
Shouldn't be done like this. Instead should be
```php
    <?php endif; ?>
<?php endforeach; ?>
```

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/attributes.phtml
> +        <?php endif; endforeach; ?>
Same as above.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/composer.json
> +{
We don't usually keep around the `composer.json` inside out own custom modules.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/registration.php
> +/**
Missing copyright block.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/requirejs-config.js
> +var config = {
Missing copyright block.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/theme.xml
> +<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
Missing copyright block.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/layout/catalog_product_view_type_simple.xml
> +<!--
You can replace the docblock.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/layout/catalog_product_view_type_simple.xml
> +        <attribute name="class" value="magebit-product-simple"/>
Pretty sure this is an invalid node type. But could be mistaking.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +                        <script type="text/x-magento-init">
Line indentions looks to be incorrect.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Theme/layout/default.xml
> +<?xml version="1.0"?>
Missing copyright block.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/web/js/qty-counter.js
> +'use strict';
Missing copyright block.

2023-10-09 07:59 UTC, ronaldsrmagebit commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/type/stock_info.phtml
> +/**
The copyright block can be replaced.
This looks to be a copy-paste from Magento. Probably can highlight what was changed.

2023-10-09 08:02 UTC, ronaldsrmagebit commented
Some additional things.

I would strongly suggest using Magento PHP code sniffer as it comes with it.
```
vendor/bin/phpcs --parallel=4 --standard=Magento2 app/design/frontend/Magebit app/code/Magebit -s
```

2023-10-09 17:26 UTC, EglitisMaikls commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/type/stock_info.phtml
> +/**
Integrated quantity of items available which was not available by default.

2023-10-09 17:31 UTC, EglitisMaikls commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/list/items.phtml
> +/**
Changes were made in rule-set for 'related' and 'upsell', no significant changes in rest of the code.

2023-10-09 17:55 UTC, EglitisMaikls commented on app/design/frontend/Magebit/learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +/**
Integrated quantity increment script, added child block which shows stock availability.

2023-10-09 18:08 UTC, EglitisMaikls commented on app/design/frontend/Magebit/learning/Magento_Catalog/layout/catalog_product_view_type_simple.xml
> +        <attribute name="class" value="magebit-product-simple"/>
Defined custom body class for styling simple product pages only. I'm sure there must be another approach to archieve that.

2023-10-10 09:15 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/Block/Widget/PageList.php
> +        SearchCriteriaBuilder $searchCriteriaBuilder,
This can be promoted property to, same as PageRepositoryInterface

2023-10-10 09:19 UTC, ronaldsrmagebit commented on app/code/Magebit/PageListWidget/view/frontend/templates/page-list.phtml
> +
Unnecessary new lines

2023-10-11 13:20 UTC, ronaldsrmagebit approved these changes

2023-10-11 13:20 UTC, merged